### ISSUE TITLE
请问用的是哪个模型？

### ISSUE THREAD

**Issue by PineREN** [zlmo/mmpose_mnn#1]
您好，请问用的mmpose哪个模型？是通过mmpose上的转成onnx，还是mmdeploy上转成onnx的？能分享一下您转好的模型嘛？因为我现在测了几个模型，都能出结果，就是点完全不准。谢谢您。

**Comment by zlmo** [comment]
Top-down的应该都可以，像simplebaseline。不过这个代码只是整个topdown流程的pose检测部分，前面目标检测（ssd、yolo）的部分还没加，我是手动指定box坐标，‘std::vector<float> box_coords = {283.0, 44.0, 499.0, 384.0};’，点不准可能跟这个有关。

**Comment by PineREN** [comment]
嗯嗯，谢谢您回复，我也手动指定了box_coords,但仍然不准，所以应该不是这个问题。我是用的top-down中Hrnet 、RSN。您是通过哪种方法转成onnx的呐？能分享一下您转的mnn模型吗？

**Comment by zlmo** [comment]
这个代码比较早了，模型已经删了。不过当时是对着mmpose的python代码一行行改的，中间函数都能对应上，可以在python代码和c++代码相同的地方（预处理、后处理）把一些中间结果打印一下，就大概能确定哪里出问题了。
